################################################################################
# Lattice RISC-V RX platform integration                                       #
################################################################################

# Toolchain prefix (can be overridden by the user)
RISCV_PREFIX          ?= riscv-none-embed-

override AR           = $(RISCV_PREFIX)ar
override AS           = $(RISCV_PREFIX)gcc
override CC           = $(RISCV_PREFIX)gcc
override OC           = $(RISCV_PREFIX)objcopy
override SIZE         = $(RISCV_PREFIX)size
override OBJDUMP      = $(RISCV_PREFIX)objdump
override GDB          = $(RISCV_PREFIX)gdb
SREC_CAT              ?= srec_cat
LATTICE_BSP_PATH      ?=

################################################################################
#                      C library / specs selection                              #
################################################################################

LIBC ?= newlib
ifeq ($(LIBC),newlib)
LIBC_SPECS   := --specs=nosys.specs
LIBC_DEFINES :=
else ifeq ($(LIBC),newlib-nano)
LIBC_SPECS   := --specs=nano.specs
LIBC_DEFINES :=
else ifeq ($(LIBC),picolibc)
LIBC_SPECS   := --specs=picolibc.specs
LIBC_DEFINES := -DPICOLIBC_DOUBLE_PRINTF_SCANF
else
$(error Unsupported LIBC '$(LIBC)'; use newlib, newlib-nano or picolibc)
endif

################################################################################
#                            Compiler / Linker flags                            #
################################################################################

LATTICE_ARCH_FLAGS   ?= -march=rv32imac -mabi=ilp32 -msmall-data-limit=8 -mno-save-restore
LATTICE_DEBUG        ?= n
LATTICE_OPT_FLAGS    ?= -Os
ifeq (y,$(strip $(LATTICE_DEBUG)))
LATTICE_OPT_FLAGS := -O0 -g3
endif
LATTICE_COMMON_FLAGS ?= $(LATTICE_OPT_FLAGS) -fmessage-length=0 -fsigned-char \
	   -ffunction-sections -fdata-sections
LATTICE_DEFINES      ?= -DLATTICE_PLATFORM
LATTICE_CSTD         ?= -std=gnu11
LATTICE_ASFLAGS      ?= -x assembler-with-cpp
LATTICE_LDFLAGS      ?= -nostartfiles -Xlinker --gc-sections
LATTICE_MAP          ?= $(BUILD_DIR)/$(BINARY_FILE_NAME).map
LATTICE_LST          ?= $(BUILD_DIR)/$(BINARY_FILE_NAME).lst
LATTICE_SIZ          ?= $(BUILD_DIR)/$(BINARY_FILE_NAME).siz
LATTICE_BIN          ?= $(BUILD_DIR)/$(BINARY_FILE_NAME).bin
LATTICE_MEM          ?= $(BUILD_DIR)/$(BINARY_FILE_NAME).mem

CFLAGS  += $(LATTICE_ARCH_FLAGS) $(LATTICE_COMMON_FLAGS) $(LATTICE_CSTD) \
	   $(LATTICE_DEFINES) $(LIBC_DEFINES) $(LIBC_SPECS)
ASFLAGS += $(LATTICE_ARCH_FLAGS) $(LATTICE_COMMON_FLAGS) $(LATTICE_ASFLAGS) \
	   $(LATTICE_DEFINES) $(LIBC_DEFINES) $(LIBC_SPECS)
LDFLAGS += $(LATTICE_ARCH_FLAGS) $(LATTICE_COMMON_FLAGS) $(LATTICE_LDFLAGS) \
	   -Wl,-Map,$(LATTICE_MAP) $(LIBC_SPECS)

################################################################################
#                      Linker script (can be overridden)                        #
################################################################################

LATTICE_LINKER_SCRIPT ?= $(PROJECT)/src/platform/$(PLATFORM)/linker.ld
ifneq (,$(wildcard $(LATTICE_LINKER_SCRIPT)))
LSCRIPT ?= $(LATTICE_LINKER_SCRIPT)
endif

################################################################################
#                  Optional BSP sources pulled into the build                   #
################################################################################

# LATTICE_BSP_PATH can be a space-separated list of directories containing BSP
# sources (C/S) and headers generated by Propel. When not provided, fall back to
# $(PROJECT)/bsp if it exists. These directories are appended to SRC_DIRS so
# generic.mk will automatically discover all source / header files beneath them.
ifneq ($(strip $(LATTICE_BSP_PATH)),)
BSP_DIRS := $(LATTICE_BSP_PATH)
else
$(info [lattice] LATTICE_BSP_PATH is not set; define it to pull Propel BSP sources.)
ifneq (,$(wildcard $(PROJECT)/bsp))
BSP_DIRS := $(PROJECT)/bsp
endif
endif

ifneq ($(strip $(BSP_DIRS)),)
$(foreach bsp,$(BSP_DIRS),$(if $(wildcard $(bsp)),$(eval SRC_DIRS += $(bsp)),$(warning [lattice] Ignoring missing BSP directory '$(bsp)')))
endif

################################################################################
#                          Convenience platform targets                         #
################################################################################

.PHONY: lattice_run lattice_sdkbuild lattice_sdkclean lattice_sdkopen lattice_post_build
.PHONY: lattice_project

lattice_run:
	$(call print,lattice_run is not implemented; use make run hooks for your board)

lattice_sdkbuild lattice_sdkclean lattice_sdkopen:
	@true

lattice_post_build:
	$(call print,Generating lattice artifacts)
	$(OBJDUMP) --source --all-headers --demangle --line-numbers --wide $(BINARY) > $(LATTICE_LST)
	$(SIZE) --format=berkeley $(BINARY) > $(LATTICE_SIZ)
	$(OC) -O binary --gap-fill 0 $(BINARY) $(LATTICE_BIN)
	$(SREC_CAT) $(LATTICE_BIN) -Binary -byte-swap 4 -DISable Header -Output $(LATTICE_MEM) -MEM 32

lattice_project:
	$(call mk_dir,$(BUILD_DIR))
